export const globalActionTypes = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LIGHT_THEME: 'LIGHT_THEME',
  DARK_THEME: 'DARK_THEME',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  ENABLE_GEO: 'ENABLE_GEO',
  DISABLE_GEO: 'DISABLE_GEO',
};
